
#spring.mvc.static-path-pattern: /static/**


spring:
  servlet:
    multipart:
      enabled: true
      location: ${java.io.tmpdir}
      maxFileSize: 10MB  #파일의 최대 사이즈
      maxRequestSize: 20MB  #요청한 최대 사이즈
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF/jsp
      suffix: .jsp
     
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hyamstagram?serverTimeZone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    
  
        